package config

import (
	"fmt"
	"os"
	"path/filepath"
)

// defaultTOML is the content written by config init. It documents every field
// and produces VS Code .code-workspace files out of the box.
const defaultTOML = `# Files copied from the source worktree into newly-created worktrees.
[sync]
files = [
  ".claude/settings.local.json",
  ".env",
  ".env.docker-compose",
  ".vscode/settings.json",
  ".vscode/tasks.json",
  ".vscode/launch.json",
  ".vscode/extensions.json",
  ".vscode/*.code-snippets",
]

# Per-worktree artifact generated by treepad sync and treepad new.
# Remove this section to skip artifact generation (e.g. for JetBrains / Neovim).
[artifact]
filename = "{{.Slug}}-{{.Branch}}.code-workspace"
content = """
{
  "folders": [
    {{- range $i, $w := .Worktrees}}
    {{- if $i}},{{end}}
    {"name": "{{$w.Branch}}", "path": "{{$w.RelPath}}"}
    {{- end}}
  ]
}
"""

# Command run when --open is passed to treepad new.
# {{.ArtifactPath}} is the absolute path of the generated artifact, or the
# worktree directory when no [artifact] section is configured.
[open]
command = ["open", "{{.ArtifactPath}}"]

# Configuration for tp from-spec. Resolves a spec body (from --issue or
# --file), renders a prompt into the worktree, then hands off to an agent.
# Template data: .Spec, .Skills, .Branch, .Slug, .WorktreePath, .PromptPath.
# .Prompt (rendered body) is additionally available in agent_command templates.
[from_spec]
prompt_filename = "PROMPT.md"
skills = []
agent_command = ["claude", "{{.PromptPath}}"]
prompt_template = """
# {{.Branch}}

## Spec
{{.Spec}}

## Skills to invoke
{{range .Skills}}- /{{.}}
{{end}}
"""
`

// WriteDefault writes a config file populated with documented defaults.
// If global is true, writes to the global config path (XDG or $TREEPAD_CONFIG).
// Otherwise writes .treepad.toml in dir. Returns the path written.
func WriteDefault(dir string, global bool) (string, error) {
	var path string
	if global {
		p, err := GlobalConfigPath()
		if err != nil {
			return "", err
		}
		path = p
	} else {
		path = filepath.Join(dir, configFileName)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("create config directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(defaultTOML), 0o644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}
	return path, nil
}
